print ("------------------------------------------------")
print ("*            ====CARDE HOTHEAFA====            *")
print ("------------------------------------------------")
print ("Name:","Hotheafa Sayf Ihdoush")
print ("University Major:","Cyberdsecurity")
print ("Degree:","Bachelor's Degree")
print ("Year Number:","1")
print ("Student ID Number :","26-1083")
print ("Housing :","Surif")
print ("Phone Number:","0592118597")
print ("University Emial:","261083@ppu.edu.ps")
print ("------------------------------------------------")
print ("------------------------------------------------")